spring.application.name=ms-pedidos
server.port=8081

spring.datasource.url=jdbc:h2:mem:pedidosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

services.inventario.base-url=http://localhost:8082
services.inventario.reserve-path=/api/inventario/reservar
services.inventario.release-path=/api/inventario/liberar
services.pagos.base-url=http://localhost:8083
services.pagos.charge-path=/api/pagos
services.notificaciones.base-url=http://localhost:8084
services.notificaciones.send-path=/api/notificaciones
